### ISSUE TITLE
Problem with ignoreFirst

### ISSUE THREAD

**Issue by vrenda16** [KurozeroPB/RssEmitter#1]
Hello, so i have a problem when i use rss-emitter-ts with more than one rss url. I use the option ignoreFirst: true but for the first url work and for the others don't work. Some help?

**Comment by MCheca** [comment]
I have the same problem, I have fixed it deleting some lines of code, you can see my fork https://github.com/MCheca/RssEmitter it works for me

**Comment by Pepijn98** [comment]
Sorry I'm so late on this, I got a better fix that does not include removing the whole else block since that will break other code.

**Comment by Pepijn98** [comment]
Version 0.4.2 has been published to npm, please let me know if it didn't fix it for you.
