### ISSUE TITLE
Way to distinguish which feed emitted the new item

### ISSUE THREAD

**Issue by abdatta** [KurozeroPB/RssEmitter#2]
Hi,

When I supply an array of feeds and the emitter returns the new item, I cannot know which feed generated that new item (and have to use hacks to manage). A better way will be if you support custom event names for each feed, and for a new item in a feed, it's the corresponding event will be called. For feeds with no event name provided, the default can be `item:new`.

If you want, I can do a PR.

Thanks in advance.

**Comment by Pepijn98** [comment]
Sounds like a good idea, a PR is appreciated!

**Comment by Pepijn98** [comment]
Added in #3
